/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.msudenver.bluejext.qualitytools;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
